name: build
on:
  push:
  workflow_dispatch:

env:
  HOMEBREW_DEVELOPER: 1

jobs:
  build:
    name: build
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - libkeyfinder
          - keyfinder-cli
          - tremc
          - things3-cloud

    steps:
      - uses: actions/checkout@v3

      - name: Build package
        run: |
          rm -rf /usr/local/include/c++
          FORMULA=./${{ matrix.package }}.rb
          if brew info --json=v2 --formula "$FORMULA" | python3 -c "import sys,json; exit(0 if json.load(sys.stdin)['formulae'][0]['versions']['bottle'] else 1)"; then
            brew install --force --formula "$FORMULA"
            brew uninstall ${{ matrix.package }}
          fi
          brew install --force --build-from-source --formula "$FORMULA"
