name: build
on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: build
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - libkeyfinder
          - keyfinder-cli
          - tremc

    steps:
      - uses: actions/checkout@v3

      - name: Build package
        run: |
          rm -rf /usr/local/include/c++
          brew tap evanpurkhiser/personal
          brew install --force --build-from-source ./${{ matrix.package}}.rb
